[build-system]
requires = ["setuptools", "setuptools_scm[toml]"]
build-backend = "setuptools.build_meta"

[project]
name = "saguaro-pipeline"
<<<<<<< Updated upstream
version = "2.1.7"
=======
version = "2.2.1"
>>>>>>> Stashed changes
readme = "README.md"
license.file = "LICENSE"
dynamic = ["dependencies"]

[project.scripts]
median-watcher = "saguaro_pipeline.median_watcher:cli"
saguaro-pipe = "saguaro_pipeline.saguaro_pipe:cli"

[tool.setuptools.dynamic]
dependencies.file = "requirements.txt"

[tool.setuptools_scm]
